version: '3'
services:
    blockchain:
        build: .
        container_name: BLOCKCHAIN
        restart: always
        ports:
            - 80:80
        volumes:
            - web-data:/home/ubuntu/app/

volumes:
    web-data: